services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm-host2-stillcrazy-pro
    restart: always
    ports:
      - $HTTP_PORT:80  # HTTP
      - $HTTPS_PORT:443 # HTTPS
      - $WEBUI_PORT:81  # Web UI
    volumes:
      - /opt/volumes/npm-host2-stillcrazy-pro/data:/data
      - /opt/volumes/npm-host2-stillcrazy-pro/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=America/Los_Angeles
      - DISABLE_IPV6=true
      - PUID=1000
      - PGID=1000
    networks:
      - npm_network

networks:
  npm_network:
    external: true
