services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: budget-alannadailey-com
    networks:
      - npm_network
    volumes:
      - /opt/volumes/budget-alannadailey-com/data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  npm_network:
    external: true
