services:
  db:
    image: postgres:16
    container_name: ${APP_PATH}-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - ${APP_PATH}-net

  app:
    image: joplin/server:latest
    container_name: ${APP_PATH}-app
    depends_on:
      - db
    ports:
      - $APP_PORT:22300  # External access for Joplin API
    restart: unless-stopped
    environment:
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=${DB_CLIENT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${APP_PATH}-db
    networks:
      - ${APP_PATH}-net

networks:
  joplin-net:
    name: ${APP_PATH}-net