services:
  unifi-db:
    image: docker.io/mongo:8.0
    container_name: ${HOST}-unifi-db
    networks:
      - dcci-unifi-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_DBNAME=$MONGO_DBNAME
      - MONGO_AUTHSOURCE=$MONGO_AUTHSOURCE
    volumes:
      - /opt/volumes/${HOST}-unifi/db:/data/db
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: ${HOST}-unifi-app
    networks:
      - dcci-unifi-network
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_HOST=${HOST}-unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=$MONGO_DBNAME
      - MONGO_AUTHSOURCE=$MONGO_AUTHSOURCE
      - UNIFI_HTTP_PORT_OVERRIDE=8443
    volumes:
      - /opt/volumes/${HOST}-unifi/data:/config
networks:
  dcci-unifi-network:
    driver: bridge
  proxy:
    external: true