services:
  unifi-db:
    image: docker.io/mongo:7.0
    container_name: dcci-unifi-db
    networks:
      - dcci-unifi-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_AUTHSOURCE=${MONGO_AUTHSOURCE}
    volumes:
      - /opt/volumes/dcci-unifi/db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro # Runs the first time only to initialize the database
    restart: unless-stopped

  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: dcci-unifi-app
    networks:
      - dcci-unifi-network
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=dcci-unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MONGO_AUTHSOURCE=${MONGO_AUTHSOURCE}
    volumes:
      - /opt/volumes/dcci-unifi/data:/config
    ports:
        # Required Unifi Ports
      - "3478/udp"    # STUN
      - "10001/udp"   # Discovery
      - "8080/tcp"    # Inform
      - "8443/tcp"    # HTTPS GUI
        # Optional Unifi Ports
      - "8843/tcp"    # HTTPS Guest Portal
      - "8880/tcp"    # HTTP Guest Portal
      - "6789/tcp"    # Speedtest
      - "5514/udp"    # Remote Syslog
    restart: unless-stopped

networks:
  dcci-unifi-network:
    driver: bridge
  proxy:
    external: true