# Defaule docker compose file for running Headscale, with Headplane as a web gui
# Headscale default listening port is 8080
# Headplane default listening port is 3000
services:
  headscale:
    container_name: vpn-stillcrazy-pro
    image: headscale/headscale:stable
    restart: unless-stopped
    networks:
      - npm_network
      - headscale_net
    volumes:
      - /opt/volumes/vpn-stillcrazy-pro/config:/etc/headscale
      - /opt/volumes/vpn-stillcrazy-pro/data:/var/lib/headscale
    entrypoint: headscale serve

  headplane:
    image: ghcr.io/tale/headplane:0.5.10
    container_name: headplane
    restart: unless-stopped
    networks:
      - npm_network
      - headscale_net
    volumes:
      - '/opt/volumes/vpn-stillcrazy-pro/config/config.yaml:/etc/headscale/config.yaml'
      - '/opt/volumes/vpn-stillcrazy-pro/config/headplaneconfig.yaml:/etc/headplane/config.yaml'
      - '/opt/volumes/vpn-stillcrazy-pro/headplane-data:/var/lib/headplane'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  npm_network:
    external: true
  headscale_net: